package geo

import (
	_ "embed"
	"encoding/csv"
	"strconv"
	"strings"
	"sync"
)

// centroidsCSV is generated by internal/gencentroids from Natural Earth; do not edit by hand.
//
//go:embed centroids.csv
var centroidsCSV string

type latLng struct{ lat, lng float64 }

// centroidTable parses the embedded CSV once into an immutable map.
var centroidTable = sync.OnceValue(func() map[string]latLng {
	records, err := csv.NewReader(strings.NewReader(centroidsCSV)).ReadAll()
	if err != nil {
		panic("geo: embedded centroids.csv is malformed: " + err.Error())
	}
	m := make(map[string]latLng, len(records))
	for i, r := range records {
		if i == 0 || len(r) != 3 {
			continue // header
		}
		lat, err1 := strconv.ParseFloat(r[1], 64)
		lng, err2 := strconv.ParseFloat(r[2], 64)
		if err1 != nil || err2 != nil {
			panic("geo: bad centroid row for " + r[0])
		}
		m[r[0]] = latLng{lat, lng}
	}
	return m
})

// Centroid returns the label point of the country with ISO 3166-1 alpha-2 code iso2.
func Centroid(iso2 string) (lat, lng float64, ok bool) {
	c, ok := centroidTable()[strings.ToUpper(iso2)]
	return c.lat, c.lng, ok
}
